// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions solo estan configuradas para android y web.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8J1l438u0VOnbauKct38w1Pu2TvJVPGc',
    appId: '1:2143866903:web:754ff6281506b5e4544c52',
    messagingSenderId: '2143866903',
    projectId: 'frontacueductonewzenda',
    authDomain: 'frontacueductonewzenda.firebaseapp.com',
    storageBucket: 'frontacueductonewzenda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcrhnDPCZgCI1obcJ72JIVZb7rPqn5NOI',
    appId: '1:2143866903:android:251a4add47363bf1544c52',
    messagingSenderId: '2143866903',
    projectId: 'frontacueductonewzenda',
    storageBucket: 'frontacueductonewzenda.firebasestorage.app',
  );
}
